name: Suggestions
description: Have new features to suggest? Accepting ideas here!
title: "[Suggest] "
body:
  - type: markdown
    attributes:
      value: |
        ### Guidelines
        Be sure to read the Contributing Guidelines and Code of Conduct before opening a new issue.
        To report a security vulnerability, please review our Security Policy for more details.
  - type: textarea
    attributes:
      label: Suggestion
      description: |
        Enter your suggestion here. Try to be as thorough as possible.
        You can also help us improve by pulling a request which correct or improve some of the codes in the corresponding repository.
        If applicable, add screenshots to help explain your suggestion.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reason
      description: Tell us why you are suggesting this.
      placeholder: "I'm suggesting this because..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Other
      description: |
        Have anything else to add?
        Let us know if you have any additional feedback!
    validations:
      required: false
      
